#pragma once

#include "Playground.h"

Playground level1 = {
  { { 2, 0 }, { FieldValue::Wall } },
  { { 3, 0 }, { FieldValue::Wall } },
  { { 4, 0 }, { FieldValue::Wall } },
  { { 4, 1 }, { FieldValue::Wall } },
  { { 4, 2 }, { FieldValue::Wall } },
  { { 5, 2 }, { FieldValue::Wall } },
  { { 6, 2 }, { FieldValue::Wall } },
  { { 7, 2 }, { FieldValue::Wall } },
  { { 7, 3 }, { FieldValue::Wall } },
  { { 7, 4 }, { FieldValue::Wall } },
  { { 7, 4 }, { FieldValue::Wall } },
  { { 6, 4 }, { FieldValue::Wall } },
  { { 5, 4 }, { FieldValue::Wall } },
  { { 5, 5 }, { FieldValue::Wall } },
  { { 5, 6 }, { FieldValue::Wall } },
  { { 5, 7 }, { FieldValue::Wall } },
  { { 4, 7 }, { FieldValue::Wall } },
  { { 3, 7 }, { FieldValue::Wall } },
  { { 3, 6 }, { FieldValue::Wall } },
  { { 3, 5 }, { FieldValue::Wall } },
  { { 2, 5 }, { FieldValue::Wall } },
  { { 1, 5 }, { FieldValue::Wall } },
  { { 0, 5 }, { FieldValue::Wall } },
  { { 0, 4 }, { FieldValue::Wall } },
  { { 0, 3 }, { FieldValue::Wall } },
  { { 1, 3 }, { FieldValue::Wall } },
  { { 2, 3 }, { FieldValue::Wall } },
  { { 2, 2 }, { FieldValue::Wall } },
  { { 2, 1 }, { FieldValue::Wall } },
  { { 3, 2 }, { FieldValue::Space } },
  { { 2, 4 }, { FieldValue::Space } },
  { { 4, 3 }, { FieldValue::Space } },
  { { 3, 3 }, { FieldValue::Space, FieldValue::Box } },
  { { 3, 4 }, { FieldValue::Space, FieldValue::Box } },
  { { 4, 5 }, { FieldValue::Space, FieldValue::Box } },
  { { 5, 3 }, { FieldValue::Space, FieldValue::Box } },
  { { 3, 1 }, { FieldValue::Space, FieldValue::Target } },
  { { 6, 3 }, { FieldValue::Space, FieldValue::Target } },
  { { 1, 4 }, { FieldValue::Space, FieldValue::Target } },
  { { 4, 6 }, { FieldValue::Space, FieldValue::Target } },
  { { 4, 4 }, { FieldValue::Space, FieldValue::Player } }
};
